# Centralised error-reason constants.
# Using these instead of bare strings prevents typos and simplifies refactoring.

WRONG_FORMAT       = "WRONG-FORMAT"
WRONG_DATA         = "WRONG-DATA"
USER_UNKNOWN       = "USER-UNKNOWN"
WRONG_SECRET       = "WRONG-SECRET"
SECRET_EXPIRED     = "SECRET-EXPIRED"
ALREADY_EXISTS     = "ALREADY-EXISTS"
USER_EMPLOYED      = "USER-EMPLOYED"
ALREADY_UNEMPLOYED = "ALREADY-UNEMPLOYED"
ALREADY_EMPLOYED   = "ALREADY-EMPLOYED"
FUNCTION_UNKNOWN   = "FUNCTION-UNKNOWN"
FUNCSET_UNKNOWN    = "FUNCSET-UNKNOWN"
ROLE_UNKNOWN       = "ROLE-UNKNOWN"
PROP_UNKNOWN       = "PROP-UNKNOWN"
BRANCH_UNKNOWN     = "BRANCH-UNKNOWN"
AGENT_UNKNOWN      = "AGENT-UNKNOWN"
NOT_IN_SET         = "NOT-IN-SET"
NOT_ALLOWED        = "NOT-ALLOWED"
NO_VACANT_POS      = "NO-VACANT-POSITIONS"
DATABASE_ERROR     = "DATABASE-ERROR"
OP_UNAUTHORIZED    = "OP-UNAUTHORIZED"
OP_UNKNOWN         = "OPERATOR-UNKNOWN"
FORBIDDEN_FOR_OP   = "FORBIDDEN-FOR-OP"

# Mapping from reason code to HTTP status
REASON_TO_HTTP = {
    WRONG_FORMAT       : 400,
    WRONG_DATA         : 400,
    USER_UNKNOWN       : 401,
    WRONG_SECRET       : 403,
    SECRET_EXPIRED     : 403,
    ALREADY_EXISTS     : 403,
    USER_EMPLOYED      : 403,
    ALREADY_UNEMPLOYED : 403,
    FUNCTION_UNKNOWN   : 404,
    FUNCSET_UNKNOWN    : 404,
    ROLE_UNKNOWN       : 404,
    PROP_UNKNOWN       : 404,
    BRANCH_UNKNOWN     : 404,
    AGENT_UNKNOWN      : 404,
    NOT_IN_SET         : 404,
    NOT_ALLOWED        : 405,
    DATABASE_ERROR     : 500,
    OP_UNAUTHORIZED    : 401,
    OP_UNKNOWN         : 401,
    FORBIDDEN_FOR_OP   : 403,
}
