version: 1 # must have for dictConfig

#-------------------------------------------------------------
# How to present:

formatters:

  forView:
    format: "[%(asctime)s] %(levelname)s %(name)s: %(message)s"
    datefmt: "%H:%M:%S"

  forDisk: 
    format: "[%(asctime)s] %(levelname)-8s %(name)-15s: %(message)s"

#-------------------------------------------------------------
# Where to put:

handlers:

  hCons: 
    class: logging.StreamHandler
    formatter: forView
    level: DEBUG

  hDisk: 
    class: logging.handlers.RotatingFileHandler
    formatter: forDisk
    level: INFO
    filename: LOGS/aac.log
    maxBytes: 10000000
    backupCount: 99
    encoding: UTF-8 

#-------------------------------------------------------------
# What to take:

loggers:
  # for all 3rd party libraries:
  root: 
    level: INFO
    handlers: [hCons,hDisk]
  # for our handmade modules:
  aac:
    level: DEBUG
    handlers: [hCons,hDisk]
    propagate: 0 #don't pass logged events to higher level (like root) too
  dataKeeper:
    level: INFO
    handlers: [hCons,hDisk]
    propagate: 0 #don't pass logged events to higher level (like root) too
  agentsKeeper:
    level: INFO
    handlers: [hCons,hDisk]
    propagate: 0 #don't pass logged events to higher level (like root) too
  testRunner:
    level: INFO
    handlers: [hCons,hDisk]
    propagate: 0 #don't pass logged events to higher level (like root) too


#-------------------------------------------------------------
